import { CAREER_TAXONOMY_VERSION, type ProjectCareerMapping } from "./taxonomy.js";

const m = (
  targetRoleIds: string[],
  competencyIds: string[],
  portfolioSignalIds: string[],
  requiredToolIds: string[],
  accessRequirementIds: string[],
  recommendedExperienceLevels: string[],
): ProjectCareerMapping => ({
  targetRoleIds,
  competencyIds,
  portfolioSignalIds,
  requiredToolIds,
  accessRequirementIds,
  recommendedExperienceLevels,
  careerTaxonomyVersion: CAREER_TAXONOMY_VERSION,
});

export const PILOT_CAREER_MAPPINGS_V1: Readonly<Record<string, ProjectCareerMapping>> = {
  P001: m(
    ["software-developer", "backend-developer"],
    ["api-integration", "json-processing", "command-line-interface"],
    ["code-repository", "technical-documentation"],
    ["python", "git-github"],
    ["computer-internet", "public-dataset"],
    ["BEGINNER"],
  ),
  P004: m(
    ["full-stack-developer", "software-developer"],
    ["react-development", "node-development", "rest-api-design", "postgresql", "authentication", "deployment"],
    ["deployed-application", "code-repository", "technical-documentation"],
    ["react-node", "postgresql", "git-github"],
    ["computer-internet", "free-cloud-account"],
    ["INTERMEDIATE"],
  ),
  P006: m(
    ["frontend-developer", "web-developer"],
    ["responsive-web-design", "web-content-publishing", "deployment"],
    ["deployed-application", "code-repository"],
    ["nextjs-astro", "git-github"],
    ["computer-internet", "free-cloud-account"],
    ["BEGINNER"],
  ),
  P007: m(
    ["backend-developer", "api-developer"],
    ["node-development", "rest-api-design", "jwt-security", "api-documentation", "deployment"],
    ["deployed-application", "code-repository", "technical-documentation"],
    ["node-express", "postman", "git-github"],
    ["computer-internet", "free-cloud-account"],
    ["INTERMEDIATE"],
  ),
  P014: m(
    ["data-scientist"],
    ["data-cleaning", "predictive-modeling", "feature-engineering", "model-evaluation"],
    ["model-evaluation", "code-repository"],
    ["python", "jupyter", "pandas-sklearn"],
    ["computer-internet", "public-dataset"],
    ["BEGINNER"],
  ),
  P019: m(
    ["nlp-analyst", "data-scientist"],
    ["natural-language-processing", "data-visualization", "data-storytelling"],
    ["data-analysis", "dashboard"],
    ["python", "jupyter", "nlp-library"],
    ["computer-internet", "public-dataset"],
    ["BEGINNER"],
  ),
  P022: m(
    ["responsible-ai-analyst", "data-scientist"],
    ["fairness-evaluation", "subgroup-analysis", "mitigation-analysis", "model-evaluation"],
    ["audit-report", "code-repository"],
    ["python", "jupyter", "fairness-library"],
    ["computer-internet", "public-dataset"],
    ["INTERMEDIATE"],
  ),
  P023: m(
    ["data-analyst", "public-health-analyst"],
    ["data-cleaning", "correlation-analysis", "data-storytelling"],
    ["data-analysis", "strategy-memo"],
    ["python", "jupyter", "spreadsheet"],
    ["computer-internet", "public-dataset"],
    ["BEGINNER"],
  ),
  P027: m(
    ["data-analyst", "marketing-analyst"],
    ["hypothesis-testing", "effect-size-analysis", "data-storytelling"],
    ["data-analysis", "strategy-memo"],
    ["python", "jupyter", "spreadsheet"],
    ["computer-internet", "public-dataset"],
    ["INTERMEDIATE"],
  ),
  P028: m(
    ["data-analyst", "business-analyst"],
    ["data-cleaning", "predictive-modeling", "model-evaluation", "business-recommendations"],
    ["data-analysis", "strategy-memo"],
    ["python", "jupyter", "pandas-sklearn"],
    ["computer-internet", "public-dataset"],
    ["INTERMEDIATE"],
  ),
  P029: m(
    ["sustainability-analyst", "data-analyst"],
    ["spreadsheet-modeling", "formula-design", "data-storytelling"],
    ["spreadsheet-model", "technical-documentation"],
    ["spreadsheet"],
    ["computer-internet", "public-sources"],
    ["BEGINNER"],
  ),
  P034: m(
    ["application-security-analyst"],
    ["owasp-testing", "vulnerability-reporting"],
    ["audit-report", "code-repository"],
    ["burp-suite", "git-github"],
    ["computer-internet", "local-software-install"],
    ["BEGINNER"],
  ),
  P036: m(
    ["threat-analyst", "security-analyst"],
    ["email-header-analysis", "threat-intelligence", "ioc-identification"],
    ["audit-report", "research-report"],
    ["browser", "git-github"],
    ["computer-internet", "public-sources"],
    ["BEGINNER"],
  ),
  P038: m(
    ["network-security-analyst", "security-analyst"],
    ["network-protocol-analysis", "traffic-filtering", "evidence-reporting"],
    ["audit-report", "technical-documentation"],
    ["wireshark", "git-github"],
    ["computer-internet", "local-software-install"],
    ["BEGINNER"],
  ),
  P039: m(
    ["digital-design-engineer"],
    ["digital-logic-design", "hdl-development", "fpga-toolchains"],
    ["code-repository", "engineering-simulation"],
    ["fpga-toolchain"],
    ["computer-internet", "hardware-or-simulation"],
    ["BEGINNER"],
  ),
  P040: m(
    ["embedded-systems-engineer"],
    ["embedded-programming", "sensor-integration", "circuit-prototyping"],
    ["engineering-simulation", "code-repository"],
    ["arduino-or-simulator", "git-github"],
    ["computer-internet", "hardware-or-simulation"],
    ["BEGINNER"],
  ),
  P047: m(
    ["power-electronics-engineer"],
    ["circuit-simulation", "power-control", "battery-modeling"],
    ["engineering-simulation", "technical-documentation"],
    ["ltspice", "git-github"],
    ["computer-internet", "local-software-install"],
    ["INTERMEDIATE"],
  ),
  P048: m(
    ["signal-processing-engineer"],
    ["digital-signal-processing", "frequency-analysis", "audio-processing"],
    ["engineering-simulation", "code-repository"],
    ["matlab-octave", "git-github"],
    ["computer-internet", "local-software-install"],
    ["BEGINNER"],
  ),
  P051: m(
    ["mechanical-design-engineer"],
    ["cad-modeling", "iterative-design", "design-for-manufacture"],
    ["design-case-study", "technical-documentation"],
    ["cad-software"],
    ["computer-internet", "local-software-install"],
    ["BEGINNER"],
  ),
  P052: m(
    ["mechanical-engineer"],
    ["finite-element-analysis", "material-selection", "safety-factor-analysis"],
    ["engineering-simulation", "technical-documentation"],
    ["fea-software", "cad-software"],
    ["computer-internet", "free-cloud-account", "local-software-install"],
    ["INTERMEDIATE"],
  ),
  P057: m(
    ["civil-engineer"],
    ["site-measurement", "technical-drafting", "cad-modeling"],
    ["technical-documentation", "design-case-study"],
    ["free-cad-librecad"],
    ["physical-site", "local-software-install"],
    ["BEGINNER"],
  ),
  P059: m(
    ["construction-project-engineer"],
    ["construction-scheduling", "critical-path-analysis", "resource-leveling"],
    ["operations-case-study", "technical-documentation"],
    ["project-scheduler"],
    ["computer-internet", "local-software-install"],
    ["BEGINNER"],
  ),
  P061: m(
    ["construction-estimator"],
    ["quantity-takeoff", "unit-costing", "spreadsheet-modeling"],
    ["spreadsheet-model", "strategy-memo"],
    ["takeoff-software", "spreadsheet"],
    ["computer-internet", "local-software-install"],
    ["INTERMEDIATE"],
  ),
  P063: m(
    ["financial-analyst", "investment-banking-analyst"],
    ["financial-modeling", "discounted-cash-flow", "sensitivity-analysis"],
    ["financial-model", "presentation-deck", "strategy-memo"],
    ["spreadsheet", "presentation-software"],
    ["computer-internet", "public-company-filings"],
    ["INTERMEDIATE"],
  ),
  P066: m(
    ["equity-research-analyst", "investment-banking-analyst"],
    ["investment-thesis", "comparable-analysis", "financial-modeling"],
    ["presentation-deck", "financial-model", "strategy-memo"],
    ["spreadsheet", "presentation-software"],
    ["computer-internet", "public-market-data"],
    ["INTERMEDIATE"],
  ),
  P070: m(
    ["credit-analyst", "financial-analyst"],
    ["credit-analysis", "covenant-analysis", "financial-modeling"],
    ["research-report", "spreadsheet-model"],
    ["spreadsheet", "browser"],
    ["computer-internet", "public-company-filings"],
    ["INTERMEDIATE"],
  ),
  P071: m(
    ["digital-marketing-analyst", "marketing-analyst"],
    ["campaign-planning", "audience-segmentation", "kpi-design"],
    ["strategy-memo", "presentation-deck"],
    ["canva", "spreadsheet"],
    ["computer-internet", "public-sources"],
    ["BEGINNER"],
  ),
  P076: m(
    ["brand-strategist", "marketing-analyst"],
    ["brand-analysis", "competitive-analysis", "recommendation-writing"],
    ["research-report", "strategy-memo"],
    ["browser", "presentation-software"],
    ["computer-internet", "public-sources"],
    ["BEGINNER"],
  ),
  P079: m(
    ["consulting-analyst", "market-research-analyst"],
    ["secondary-research", "industry-analysis", "executive-communication"],
    ["research-report", "presentation-deck"],
    ["browser", "presentation-software"],
    ["computer-internet", "public-sources"],
    ["INTERMEDIATE"],
  ),
  P083: m(
    ["supply-chain-analyst", "operations-analyst"],
    ["inventory-dynamics", "operations-simulation", "spreadsheet-modeling"],
    ["operations-case-study", "spreadsheet-model"],
    ["spreadsheet"],
    ["computer-internet", "public-sources"],
    ["BEGINNER"],
  ),
  P086: m(
    ["operations-analyst", "supply-chain-analyst"],
    ["layout-optimization", "capacity-planning", "business-recommendations"],
    ["operations-case-study", "technical-documentation"],
    ["diagramming-tool", "spreadsheet"],
    ["computer-internet", "public-sources"],
    ["INTERMEDIATE"],
  ),
  P087: m(
    ["real-estate-analyst", "market-research-analyst"],
    ["market-comparables", "market-metrics", "executive-communication"],
    ["research-report", "strategy-memo"],
    ["spreadsheet", "browser"],
    ["computer-internet", "public-market-data"],
    ["BEGINNER"],
  ),
  P088: m(
    ["real-estate-analyst", "financial-analyst"],
    ["real-estate-pro-forma", "investment-returns", "sensitivity-analysis"],
    ["financial-model", "strategy-memo"],
    ["spreadsheet"],
    ["computer-internet"],
    ["INTERMEDIATE"],
  ),
  P090: m(
    ["health-data-analyst", "data-analyst"],
    ["data-cleaning", "descriptive-statistics", "data-storytelling"],
    ["data-analysis", "code-repository"],
    ["python", "jupyter", "spreadsheet"],
    ["computer-internet", "public-dataset"],
    ["BEGINNER"],
  ),
  P093: m(
    ["public-health-analyst", "health-data-analyst"],
    ["kpi-design", "public-data-sourcing", "data-visualization"],
    ["dashboard", "strategy-memo"],
    ["tableau-public", "spreadsheet"],
    ["computer-internet", "public-dataset"],
    ["BEGINNER"],
  ),
  P095: m(
    ["compensation-analyst", "people-analytics-analyst"],
    ["compensation-benchmarking", "pay-range-design", "executive-communication"],
    ["spreadsheet-model", "strategy-memo"],
    ["spreadsheet", "browser"],
    ["computer-internet", "public-sources"],
    ["BEGINNER"],
  ),
  P096: m(
    ["people-analytics-analyst"],
    ["survey-design", "survey-analysis", "business-recommendations"],
    ["research-report", "strategy-memo"],
    ["survey-tool", "spreadsheet"],
    ["computer-internet"],
    ["BEGINNER"],
  ),
  P098: m(
    ["policy-analyst"],
    ["policy-writing", "stakeholder-analysis", "source-citation"],
    ["research-report", "strategy-memo"],
    ["browser", "presentation-software"],
    ["computer-internet", "public-sources"],
    ["BEGINNER"],
  ),
  P100: m(
    ["legal-analyst"],
    ["case-briefing", "legal-research", "plain-language-writing"],
    ["research-report", "strategy-memo"],
    ["legal-research", "browser"],
    ["computer-internet", "public-sources"],
    ["BEGINNER"],
  ),
  P101: m(
    ["ux-designer"],
    ["usability-evaluation", "wireframing", "prototyping"],
    ["design-case-study", "interactive-prototype"],
    ["figma"],
    ["computer-internet", "participant-or-heuristic"],
    ["BEGINNER"],
  ),
  P102: m(
    ["product-designer", "ux-designer"],
    ["usability-evaluation", "information-architecture", "prototyping", "design-systems"],
    ["design-case-study", "interactive-prototype"],
    ["figma"],
    ["computer-internet", "participant-or-heuristic"],
    ["INTERMEDIATE"],
  ),
  P104: m(
    ["accessibility-specialist", "ux-designer"],
    ["accessibility-auditing", "wcag-evaluation", "recommendation-writing"],
    ["accessibility-audit", "technical-documentation"],
    ["accessibility-tools", "browser"],
    ["computer-internet", "public-sources"],
    ["INTERMEDIATE"],
  ),
  P107: m(
    ["instructional-designer"],
    ["backward-design", "learning-assessment", "accessible-content"],
    ["educational-module", "technical-documentation"],
    ["publishing-platform", "browser"],
    ["computer-internet", "free-cloud-account"],
    ["BEGINNER"],
  ),
  P110: m(
    ["journalist"],
    ["source-verification", "investigative-research", "narrative-writing"],
    ["published-article", "research-report"],
    ["publishing-platform", "browser"],
    ["computer-internet", "public-sources"],
    ["INTERMEDIATE"],
  ),
  P111: m(
    ["video-producer"],
    ["video-preproduction", "interview-production", "video-editing"],
    ["produced-video", "technical-documentation"],
    ["video-editor"],
    ["computer-internet", "public-sources"],
    ["INTERMEDIATE"],
  ),
  P113: m(
    ["retail-analyst", "operations-analyst"],
    ["retail-conversion-analysis", "retail-layout-planning", "spreadsheet-modeling"],
    ["operations-case-study", "spreadsheet-model"],
    ["diagramming-tool", "spreadsheet"],
    ["computer-internet", "public-sources"],
    ["BEGINNER"],
  ),
  P114: m(
    ["ecommerce-specialist", "digital-marketing-analyst"],
    ["ecommerce-copywriting", "search-optimization", "image-testing"],
    ["design-case-study", "strategy-memo"],
    ["canva", "spreadsheet"],
    ["computer-internet", "public-sources"],
    ["BEGINNER"],
  ),
};
