import "dotenv/config";
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { prisma } from "../db/prisma.js";
import { normalizeSubmissionRequirements } from "../submissions/requirements.js";
import { buildCanonicalRoadmap, estimateCatalogMinutes } from "./catalog.js";
import { validateCanonicalRoadmap } from "./validation.js";

const projects = await prisma.project.findMany({
  where: { status: "PUBLISHED", moderationStatus: "APPROVED" },
  select: {
    id: true,
    title: true,
    category: true,
    difficulty: true,
    estimatedHours: true,
    deliverable: true,
    skills: true,
    skillTags: true,
    submissionRequirements: true,
  },
  orderBy: { id: "asc" },
});

const catalog = Object.fromEntries(
  projects.map((project) => {
    const requirements = normalizeSubmissionRequirements(project.submissionRequirements, project.deliverable);
    const plan = buildCanonicalRoadmap(project, requirements);
    const issues = validateCanonicalRoadmap(plan, {
      projectId: project.id,
      requiredSubmissionKeys: requirements.items.filter((item) => item.required).map((item) => item.key),
      catalogEstimatedMinutes: estimateCatalogMinutes(project.estimatedHours),
    });
    if (issues.length) throw new Error(`${project.id}: ${JSON.stringify(issues)}`);
    return [project.id, plan];
  }),
);

if (projects.length !== 139) throw new Error(`Refusing to write roadmap catalog with ${projects.length}/139 projects.`);
const outputPath = fileURLToPath(new URL("./catalog.v1.generated.ts", import.meta.url));
const output = [
  "// Generated by npm run roadmaps:catalog:generate. Review changes before committing.",
  'import type { CanonicalRoadmapPlan } from "./types.js";',
  "",
  `export const ROADMAP_CATALOG_V1: Record<string, CanonicalRoadmapPlan> = ${JSON.stringify(catalog, null, 2)};`,
  "",
].join("\n");
await writeFile(outputPath, output, "utf8");
console.log(`Wrote ${projects.length} roadmap plans to ${outputPath}`);
await prisma.$disconnect();
